funcirc:
  script:
    - paket.exe install
    - ./build_funcirc.cmd

funcirc_tests:
  script:
    - paket.exe install
    - ./build_funcirc.cmd
    - ./run_funcirc_tests.cmd

funcirc_cli:
  script:
    - paket.exe install
    - ./build_funcirc_cli.cmd

funcirc_cli_tests:
  script:
    - paket.exe install
    - ./build_funcirc_cli.cmd
    - ./run_cli_tests.cmd

funcirc_cli_performance_tests:
  script:
    - paket.exe install
    - ./run_funcirc_ptests.cmd