funcirc:
  script:
    - paket.exe install
    - ./build_funcirc.cmd

funcirc_cli:
  script:
    - paket.exe install
    - ./build_funcirc_cli.cmd

funcirc_cli_tests:
  scripts:
    - paket.exe install
    - ./build_funcirc_cli.cmd
    - ./run_cli_tests.cmd