funcirc:
  script:
    - paket.exe install
    - ./build_funcirc.cmd

funcirc_tests:
  script:
    - paket.exe install
    - ./build_funcirc.cmd
    - ./run_funcirc_tests.cmd

funcirc_performance_tests:
  script:
    - paket.exe install
    - ./run_funcirc_ptests.cmd

funcirc_cli:
  script:
    - paket.exe install
    - ./build_funcirc_cli.cmd

funcirc_cli_tests:
  script:
    - paket.exe install
    - ./build_funcirc_cli.cmd
    - ./run_cli_tests.cmd

pages:
  script:
    - paket.exe install
    - ./build_funcirc.cmd
    - docfx "Documentation/docfx_project/docfx.json"
    - mv Documentation/docfx_project/_site public
  artifacts:
    paths:
      - public
  only:
    - master